### ISSUE TITLE
Build library

### ISSUE THREAD

**Issue by karimnaaji** [NoZip/TacoGL#1]
Hey,
It would be nice to give the possibility to only build the TacoGL library without having to create a test file for it. 
Currently when I try to build without having a test file it's saying:

``` bash
[...]
-- Found GLBINDING: /usr/local/lib/libglbinding.dylib  
-- Configuring for platform MacOS without XCode, using plain make.
-- Configuring done
CMake Error at CMakeLists.txt:69 (add_executable):
  Cannot find source file:

    ~/dev/TacoGL/test/test_gl.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
[...]
```

Let me know if you're on that!

**Comment by NoZip** [comment]
The test file is now removed from the CmakeList.txt !
